project:
  type: website
  output-dir: docs

website:
  title: "Valeria's R portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://valhernandezloz06.github.io/rcc_blog_reall/
      - icon: twitter
        href: https://twitter.com/MattCrumpLab
format:
  html:
    theme: lux
    css: styles.css

editor: visual

