project:
  type: website
  output-dir: docs

website:
  title: "Valerias R portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/valhernandezloz06/rcc_blog_reall
      - icon: twitter
        href: https://twitter.com/MattCrumpLab
format:
  html:
    theme: lux
    css: styles.css

editor: visual

